name: Automated Contributions

on:
  schedule:
    - cron: '*/1 * * * *'  # Khiav txhua 1 feeb
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make daily contribution
        run: |
          echo "Making automated contribution"
          echo "$(date)" >> README.md
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Automated contribution"
          add: "README.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
